# Change these first
owner: miska # Your GitHub organization or username, where this repository lives
repo: myinfra # The name of this repository

sites:
  - name: MůjMrak
    url: https://cloud.mujmrak.cz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: upptime.myinfra.cz
  baseUrl: /myinfra
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MyInfra
  introTitle: Uptime of services provided by MyInfra hosting.
  introMessage: See whenever we do some routine maintenance or how much downtime did we had recently.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
